[separator=::]
= UML: Unified Modeling Language

== Negocios y Sistemas

* Negocios y sistemas informáticos: los negocios modernos no solo dependen de los sistemas, sino que los sistemas forman parte de los negocios.

.Los sistemas informáticos:
* ¿Soportan el negocio efectivamente?
* ¿se adaptan a las nuevas necesidades rápidamente?

.La información
* ¿Está  usada como un recurso estratégico en el negocio?
* ¿Está adecuada y/o correcta?

Necesidad: Formalizar los conocimientos de negocio.

.Atributos de información:
* Precisión
* Actualización
* 

¿Cómo modelar un negocio?

BPMN: Business Process Model and Notation

* Notación gráfica para el modelado de procesos de negocio.

UML: Unified Modeling Language, lenguaje estándar para el modelado de software

* Lenguaje estándar para el modelado de software.
* El perfil para el modelado de negocio provee un enlace *natural* entre el negocio y el sistema informático.
* 

¿Qué es UML?

* Un lenguaje de propósito general para el modelado orientado a objetos.
* Lenguaje independiente del proceso.
* Documento _OMG-UML Specification_
** OMG: Object Management Group
* UML combina notaciones provenientes desde:
** Modelado orientado a objetos
** Modelado de datos
** Modelado de componentes
** Modelado de flujos de trabajos (_workflow_)

NOTE: ¿Qué es el diagrama de clases?

NOTE: Why is it unified: 

* El lenguaje UML es un estándar OMG 

== ¿Qué es UML?

* *Es un lenguaje para visualizar:* Es algo más que un montón de símbolos gráficos. Detrás de cada símbolo en la notación de UML hay un significado bien definido. De esta manera, un desarrollador puede escribir un modelo UML, otro desarrollador, o incluso otra herramienta, puede interpretar ese modelo en ambigüedad.
* *Es un lenguaje para especificar:* Especificar se refiere a construir modelos precisos, no 
* *Es un lenguaje para construir:*
* *Es un lenguaje para documentar:*

.Claves en desarrollo de sistemas de información:
* notacion


== Problemas que presenta UML

* Falta de integración con otras técnicas (i.e. diseño de interfaces de usuario)
* Excesivamente complejo
* No es una metodología, es una notación
* No está libre de ambigüedades (el 80% de los problemas puede modelarse usando el 20% de UML)

== modelos y diagramas

* un modelo captura una vista de un sitema del mundo real
* es una abstraccion de dicho sistema, considerando un cierto proposito. asi, el modelo describe completamente aquellos aspectos del sistema que son relveantes al proposito del modelo y a un apropiado nivel de detall
* diagram: a graphic representation of a collectiion of an element of a mdoel, often drawn as a graph with vertexes and arcs

== modelos y diagramas

 