= Laboratory of Operating Systems II
:source-highlighter: highlight.js

== Exams

=== Partial 1

Reuse all the 7 nodes.

=== Partial 1 Simulation

* Realizar la implementación de una base de datos 'MariaDB' (MariaDB ya cuenta con alta disponibilidad) con alta disponibilidad.
* Use 1 balanceador (haproxy), 3 nodos de base de datos y 3 repositorios (samba).
* Se espera un gráfico explicativo (usando PlantUML)
* Un documento con un paso a paso de la implementación y evidencias del funcionamiento.

==== Solution

.Virtual machines:
* partial-ubuntu-server-master
* partial-ubuntu-server-db-1
* partial-ubuntu-server-db-2
* partial-ubuntu-server-db-3
* partial-ubuntu-server-repo-1
* partial-ubuntu-server-repo-2
* partial-ubuntu-server-repo-3

.Netplan configuration:
[source,yaml,linenums]
----
# /etc/netplan/00-installer-config.yaml
network:
    ethernet:
        eth0: # External network
            dhcp4: true
        eth1: # Internal network
            dhcp4: false
            addresses: [<Internal IP Address>]
----

.Internal IP addresses:
* partial-ubuntu-server-master: 192.168.10.10/24
* partial-ubuntu-server-db-1: 192.168.10.21/24
* partial-ubuntu-server-db-2: 192.168.10.22/24
* partial-ubuntu-server-db-3: 192.168.10.23/24
* partial-ubuntu-server-repo-1: 192.168.10.31/24
* partial-ubuntu-server-repo-2: 192.168.10.32/24
* partial-ubuntu-server-repo-3: 192.168.10.33/24

.Hostnames configuration:
[source,text]
----
# /etc/hosts
127.0.0.1 localhost
127.0.1.1 <hostname>

# Internal network

192.168.10.10/24 partial-ubuntu-server-master
192.168.10.21/24 partial-ubuntu-server-db-1
192.168.10.22/24 partial-ubuntu-server-db-2
192.168.10.23/24 partial-ubuntu-server-db-3
192.168.10.31/24 partial-ubuntu-server-repo-1
192.168.10.32/24 partial-ubuntu-server-repo-2
192.168.10.33/24 partial-ubuntu-server-repo-3

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
----

.Packages:
* haproxy: for the load balancer
* samba: for the repositories
* mariadb-server: for the database
* mariadb-client: for the database

.Haproxy configuration:
[source,conf]
----
# /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    # An alternative list with additional directives can be obtained from
    #  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3
----
.Samba configuration:
[source,conf]
----
# /etc/samba/smb.conf

----
.MariaDB configuration:

